/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MyadminRouteImport } from './routes/myadmin'
import { Route as JoinExpertRouteImport } from './routes/join-expert'
import { Route as JoinAreaPartnerRouteImport } from './routes/join-area-partner'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyadminLoginRouteImport } from './routes/myadmin.login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyadminRoute = MyadminRouteImport.update({
  id: '/myadmin',
  path: '/myadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinExpertRoute = JoinExpertRouteImport.update({
  id: '/join-expert',
  path: '/join-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAreaPartnerRoute = JoinAreaPartnerRouteImport.update({
  id: '/join-area-partner',
  path: '/join-area-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyadminLoginRoute = MyadminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MyadminRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join-area-partner': typeof JoinAreaPartnerRoute
  '/join-expert': typeof JoinExpertRoute
  '/myadmin': typeof MyadminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/myadmin/login': typeof MyadminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join-area-partner': typeof JoinAreaPartnerRoute
  '/join-expert': typeof JoinExpertRoute
  '/myadmin': typeof MyadminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/myadmin/login': typeof MyadminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join-area-partner': typeof JoinAreaPartnerRoute
  '/join-expert': typeof JoinExpertRoute
  '/myadmin': typeof MyadminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/myadmin/login': typeof MyadminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join-area-partner'
    | '/join-expert'
    | '/myadmin'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/support'
    | '/terms'
    | '/dashboard'
    | '/myadmin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join-area-partner'
    | '/join-expert'
    | '/myadmin'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/support'
    | '/terms'
    | '/dashboard'
    | '/myadmin/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join-area-partner'
    | '/join-expert'
    | '/myadmin'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/support'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/myadmin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinAreaPartnerRoute: typeof JoinAreaPartnerRoute
  JoinExpertRoute: typeof JoinExpertRoute
  MyadminRoute: typeof MyadminRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myadmin': {
      id: '/myadmin'
      path: '/myadmin'
      fullPath: '/myadmin'
      preLoaderRoute: typeof MyadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-expert': {
      id: '/join-expert'
      path: '/join-expert'
      fullPath: '/join-expert'
      preLoaderRoute: typeof JoinExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-area-partner': {
      id: '/join-area-partner'
      path: '/join-area-partner'
      fullPath: '/join-area-partner'
      preLoaderRoute: typeof JoinAreaPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myadmin/login': {
      id: '/myadmin/login'
      path: '/login'
      fullPath: '/myadmin/login'
      preLoaderRoute: typeof MyadminLoginRouteImport
      parentRoute: typeof MyadminRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MyadminRouteChildren {
  MyadminLoginRoute: typeof MyadminLoginRoute
}

const MyadminRouteChildren: MyadminRouteChildren = {
  MyadminLoginRoute: MyadminLoginRoute,
}

const MyadminRouteWithChildren =
  MyadminRoute._addFileChildren(MyadminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinAreaPartnerRoute: JoinAreaPartnerRoute,
  JoinExpertRoute: JoinExpertRoute,
  MyadminRoute: MyadminRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
